apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obsidian-saver-bot.fullname" . }}
  labels:
    {{- include "obsidian-saver-bot.labels" . | nindent 4 }}
type: Opaque
data:
  botToken: "{{ .Values.botToken | b64enc }}"
  githubToken: "{{ .Values.githubToken | b64enc }}"